# Site settings
title: Safely Report COVID-19 Exposure
email: info@safelyreport.org
url: https://safelyreport.org
#url: https://sylvaingchassang.github.io
#baseurl: /safelyreport
description: "Safely Report COVID-19 Exposure"
keywords: "workplace safety, COVID-19"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Laura Boudreau & Sylvain Chassang
  location: New York

# Build settings
markdown: kramdown
permalink: pretty

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      hide: false

# Define site.sections for markdown files
collections:
  - sections
